platzigram/platzigram/urls.py
#django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts' ), namespace='posts')),
    path('', include(('users.urls', 'users' ), namespace='users')),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

platzigram/posts/urls.py
"""POSTS URLS"""

#Django
from django.urls import path



#views
from posts import views


urlpatterns =[
    path(
    route='',
    view= views.PostFeedView.as_view(),
    name="feed"
    ),

    path(
    route='posts/new/',
    view= views.create_post,
    name="create"
    ),

    path(
    route= 'posts/<int:post_id>',
    view= views.PostDetailView.as_view(),
    name='post_detail'
    )

]

platzigram/users/urls.py
"""USERS URLS"""

# django
from django.urls import path


from users import views


urlpatterns= [

    #Posts
    path(
        route='profile/<str:username>/',
        view= views.UserDetailView.as_view(),
        name='detail'
    ),

    #Management
    path(
    route='users/login/',
    view= views.login_view,
    name="login"
    ),

    path(
    route='users/logout/',
    view= views.logout_view,
    name="logout"
    ),

    path(
    route='users/signup/',
    view= views.signup_view,
    name="signup"
    ),

    path(
    route='users/me/profile/',
    view= views.update_profile,
    name="update_profile"
    ),

]

platzigram/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt"crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/instagram.ico" %}"/>
</head>
<body>
    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock %}
    </div>
</body>
</html>

platzigram/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5"style="border-right: 1px solid #efefef" href="{% url 'posts:feed' %}">
            <img src="{% static "img/instagram.png" %}" height="45"class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="{% url "users:detail" request.user.username %}">
                      {% if request.user.profile.picture %}
                      <img src="{{ request.user.profile.picture.url }}" alt="" height="35" class="d-inline-block align-top rounded-circle">
                      {% else %}
                      <img src="{% static 'img/default-profile.png' %}"height="35"class="d-inline-block align-top rounded-circle"/>
                      {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>